// <auto-generated />
using System;
using BlazorApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260630054048_AddOrders")]
    partial class AddOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("BlazorApp.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("BlazorApp.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BlazorApp.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("BlazorApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Badge")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OriginalPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int>("Reviews")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Badge = "Sale",
                            Category = "Electronics",
                            Name = "Mechanical Keyboard Pro",
                            OriginalPrice = 249m,
                            Price = 189m,
                            Rating = 4.7999999999999998,
                            Reviews = 312
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            Name = "Noise Cancelling Headphones",
                            Price = 299m,
                            Rating = 4.9000000000000004,
                            Reviews = 876
                        },
                        new
                        {
                            Id = 3,
                            Badge = "Sale",
                            Category = "Accessories",
                            Name = "Minimalist Watch",
                            OriginalPrice = 199m,
                            Price = 159m,
                            Rating = 4.5999999999999996,
                            Reviews = 234
                        },
                        new
                        {
                            Id = 4,
                            Category = "Accessories",
                            Name = "Leather Wallet",
                            Price = 59m,
                            Rating = 4.7000000000000002,
                            Reviews = 445
                        },
                        new
                        {
                            Id = 5,
                            Badge = "New",
                            Category = "Electronics",
                            Name = "Wireless Charger",
                            Price = 45m,
                            Rating = 4.5,
                            Reviews = 189
                        },
                        new
                        {
                            Id = 6,
                            Category = "Bags",
                            Name = "Canvas Backpack",
                            Price = 89m,
                            Rating = 4.7999999999999998,
                            Reviews = 567
                        },
                        new
                        {
                            Id = 7,
                            Badge = "Sale",
                            Category = "Accessories",
                            Name = "Sunglasses UV400",
                            OriginalPrice = 99m,
                            Price = 75m,
                            Rating = 4.4000000000000004,
                            Reviews = 203
                        },
                        new
                        {
                            Id = 8,
                            Category = "Footwear",
                            Name = "Running Shoes",
                            Price = 129m,
                            Rating = 4.7000000000000002,
                            Reviews = 891
                        });
                });

            modelBuilder.Entity("BlazorApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BlazorApp.Models.OrderItem", b =>
                {
                    b.HasOne("BlazorApp.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorApp.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
